# Container Image
FROM 20.13.1-alpine

# Default directory
WORKDIR /app

# Install packages
COPY package.json .
RUN npm install

# Get application files
COPY . .

# Expose container port
EXPOSE 3334

# Start server
CMD ["node", "server.js"]